# Generated by Django 3.1.7 on 2021-03-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('salary', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='salary')),
            ],
        ),
    ]
